import torch

from origami_iros._typing import Action
from origami_iros.modules.base import BaseActionModule


class FlowMatchingActionHead(BaseActionModule[torch.Tensor]):
    def __init__(self, dim_action: int = 65) -> None:
        super().__init__(dim_action=dim_action)

    def forward(self, x: torch.Tensor) -> Action:
        """
        Args:
            x (torch.Tensor): Tensor of shape ``(batch, n_tokens, dim)`` carrying the observation tokens generated by the observation encoder.
        """
        # Process tokens
        action = ...
        return action
